# Generated by Django 5.2 on 2025-05-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='candidate_photos/')),
                ('aadhar_number', models.CharField(max_length=20)),
                ('voter_id', models.CharField(max_length=50)),
                ('manifesto', models.TextField()),
                ('supporters_names', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
